AllCops:
  TargetRubyVersion: 2.4
  Exclude: ['spec/**/*']
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/AbcSize:
  Max: 25
Metrics/MethodLength:
  Max: 15
Metrics/LineLength:
  IgnoredPatterns: ['ÈÉÊË', 'EEEE', 'raise']
Style/DoubleNegation:
  Enabled: false
